name: CI

on: [ push ]

env:
  APP_JAVA_VERSION: 17

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: ${{ env.APP_JAVA_VERSION }}
      - uses: actions/cache@v3
        name: Restore gradle cache
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.OS }}-gradle-${{ env.cache-name }}-
            ${{ runner.OS }}-gradle-
            ${{ runner.OS }}-
      - uses: actions/cache@v3
        name: Cache gradle wrapper
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
      - name: Set gradle permissions
        run: chmod +x gradlew
      - name: Check project
        run: ./gradlew check build -PgithubRepoUsername="${GITHUB_USER}" -PgithubRepoPassword="${GITHUB_TOKEN}"
        env:
          GITHUB_USER: RakSrinaNa
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@v3
        name: Upload artifact
        with:
          name: shadow-jar
          path: build/libs/mediaconverter-shaded.jar

  dropbox:
    runs-on: ubuntu-latest
    needs: build
    if:
      contains('
      refs/heads/main
      ', github.ref)
    steps:
      - uses: actions/download-artifact@v3
        name: Download artifact
        with:
          name: shadow-jar
      - name: Deploy on Dropbox
        uses: deka0106/upload-to-dropbox@v2.0.1
        with:
          dropbox_access_token: ${{ secrets.DROPBOX_DEPLOY_TOKEN }}
          src: "mediaconverter-shaded.jar"
          dest: "/Documents/JARs/MediaConverter.jar"
          mode: overwrite
